/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
**     OR EXPLICITLY MARKED SECTIONS
**
**     Project   : CCD_Car_Fish
**     Processor : MC9S12XS128MAA
**     Version   : Component 01.003, Driver 01.05, CPU db: 3.00.019
**     Datasheet : MC9S12XS256RMV1 Rev. 1.03 06/2008
**     Date/Time : 2011/1/27, 22:30
**     Abstract  :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/
/* MODULE MCUinit */

#include <MC9S12XS128.h>               /* I/O map for MC9S12XS128MAA */
#include "MCUinit.h"

/* Standard ANSI C types */
#ifndef int8_t
typedef signed char int8_t;
#endif
#ifndef int16_t
typedef signed int   int16_t;
#endif
#ifndef int32_t
typedef signed long int    int32_t;
#endif

#ifndef uint8_t
typedef unsigned char       uint8_t;
#endif
#ifndef uint16_t
typedef unsigned int  uint16_t;
#endif
#ifndef uint32_t
typedef unsigned long int   uint32_t;
#endif

#define CGM_DELAY  5119U

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
/* End of user declarations and definitions */

extern void near _Startup(void);

#pragma CODE_SEG __NEAR_SEG NON_BANKED

static void MCU_init_reset(void);
/*
** ===================================================================
**     Method      :  MCU_init_reset (component MC9S12XS256_80)
**
**     Description :
**         Device initialization code for after reset initialization.
** ===================================================================
*/
static void MCU_init_reset(void)
{

  /*  Initialization of memory configuration */
  /* MMCCTL1: MGRAMON=0,DFIFRON=0,PGMIFRON=0 */
  MMCCTL1 = 0U;                                      
  /* DIRECT: DP15=0,DP14=0,DP13=0,DP12=0,DP11=0,DP10=0,DP9=0,DP8=0 */
  DIRECT = 0U;                                      
  /* IVBR: IVB_ADDR=255 */
  IVBR = 255U;                                      
  /* ECLKCTL: NECLK=0,NCLKX2=1,DIV16=0,EDIV4=0,EDIV3=0,EDIV2=0,EDIV1=0,EDIV0=0 */
  ECLKCTL = 64U;                                      
  /* Jump to the default entry point */
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  asm jmp _Startup;
  /*lint -restore Enable MISRA rule (1.1) checking. */
} /*MCU_init*/

#pragma CODE_SEG DEFAULT
#pragma MESSAGE DISABLE C12056



/*
** ===================================================================
**     Method      :  MCU_init (component MC9S12XS256_80)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{

  /* ### MC9S12XS256_80 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,XCLKS=0,PLLWAI=0,RTIWAI=0,COPWAI=0 */
  CLKSEL = 0U;                         /* Select clock source from XTAL and set bits in CLKSEL reg. */
  /* PLLCTL: CME=1,PLLON=0,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  PLLCTL = 129U;                       /* Disable the PLL */
  /* SYNR: VCOFRQ1=0,VCOFRQ0=1,SYNDIV5=0,SYNDIV4=0,SYNDIV3=0,SYNDIV2=1,SYNDIV1=0,SYNDIV0=0 */
  SYNR = 68U;                          /* Set the multiplier register */
  /* REFDV: REFFRQ1=1,REFFRQ0=0,REFDIV5=0,REFDIV4=0,REFDIV3=0,REFDIV2=0,REFDIV1=0,REFDIV0=1 */
  REFDV = 129U;                        /* Set the divider register */
  /* POSTDIV: POSTDIV4=0,POSTDIV3=0,POSTDIV2=0,POSTDIV1=0,POSTDIV0=0 */
  POSTDIV = 0U;                        /* Set the post divider register */
  /* PLLCTL: CME=1,PLLON=1,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  PLLCTL = 193U;                                      
  while(CRGFLG_LOCK == 0U) {           /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  CLKSEL |= (unsigned char)128U;       /* Select clock source from PLL */
  /* VREGHTCL: VSEL=0,VAE=1,HTEN=0,HTDS=0,HTIE=0,HTIF=0 */
  VREGHTCL = 16U;                                      
  /* Int. priority initialization */
  /*                                        No. Address Pri XGATE Name           Description */
  INT_CFADDR = 16U;                                      
  INT_CFDATA2 = 1U;                    /*  0x0A  0xFF14   1   no   ivVReserved118 unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x0B  0xFF16   1   no   ivVReserved117 unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x0C  0xFF18   1   no   ivVReserved116 unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x0D  0xFF1A   1   no   ivVReserved115 unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x0E  0xFF1C   1   no   ivVReserved114 unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x0F  0xFF1E   1   no   ivVReserved113 unused by PE */
  INT_CFADDR = 32U;                                      
  INT_CFDATA0 = 1U;                    /*  0x10  0xFF20   1   no   ivVReserved112 unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x11  0xFF22   1   no   ivVReserved111 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x12  0xFF24   1   no   ivVReserved110 unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x13  0xFF26   1   no   ivVReserved109 unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x14  0xFF28   1   no   ivVReserved108 unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x15  0xFF2A   1   no   ivVReserved107 unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x16  0xFF2C   1   no   ivVReserved106 unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x17  0xFF2E   1   no   ivVReserved105 unused by PE */
  INT_CFADDR = 48U;                                      
  INT_CFDATA0 = 1U;                    /*  0x18  0xFF30   1   no   ivVReserved104 unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x19  0xFF32   1   no   ivVReserved103 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x1A  0xFF34   1   no   ivVReserved102 unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x1B  0xFF36   1   no   ivVReserved101 unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x1C  0xFF38   1   no   ivVReserved100 unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x1D  0xFF3A   1   no   ivVReserved99  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x1E  0xFF3C   1   no   ivVReserved98  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x1F  0xFF3E   1   no   ivVatd0compare unused by PE */
  INT_CFADDR = 64U;                                      
  INT_CFDATA0 = 1U;                    /*  0x20  0xFF40   1   no   ivVReserved96  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x21  0xFF42   1   no   ivVReserved95  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x22  0xFF44   1   no   ivVReserved94  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x23  0xFF46   1   no   ivVReserved93  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x24  0xFF48   1   no   ivVReserved92  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x25  0xFF4A   1   no   ivVReserved91  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x26  0xFF4C   1   no   ivVReserved90  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x27  0xFF4E   1   no   ivVReserved89  unused by PE */
  INT_CFADDR = 80U;                                      
  INT_CFDATA0 = 1U;                    /*  0x28  0xFF50   1   no   ivVReserved88  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x29  0xFF52   1   no   ivVReserved87  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x2A  0xFF54   1   no   ivVReserved86  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x2B  0xFF56   1   no   ivVReserved85  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x2C  0xFF58   1   no   ivVReserved84  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x2D  0xFF5A   1   no   ivVReserved83  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x2E  0xFF5C   1   no   ivVReserved82  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x2F  0xFF5E   1   no   ivVReserved81  unused by PE */
  INT_CFADDR = 96U;                                      
  INT_CFDATA0 = 1U;                    /*  0x30  0xFF60   1   no   ivVReserved79  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x31  0xFF62   1   no   ivVReserved78  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x32  0xFF64   1   no   ivVReserved77  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x33  0xFF66   1   no   ivVReserved76  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x34  0xFF68   1   no   ivVReserved75  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x35  0xFF6A   1   no   ivVReserved74  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x36  0xFF6C   1   no   ivVReserved73  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x37  0xFF6E   1   no   ivVReserved72  unused by PE */
  INT_CFADDR = 112U;                                      
  INT_CFDATA0 = 1U;                    /*  0x38  0xFF70   1   no   ivVReserved71  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x39  0xFF72   1   no   ivVReserved70  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x3A  0xFF74   1   no   ivVpit3        unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x3B  0xFF76   1   no   ivVpit2        unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x3C  0xFF78   1   no   ivVpit1        unused by PE */
  INT_CFDATA5 = 4U;                    /*  0x3D  0xFF7A   4   no   ivVpit0        used by PE */
  INT_CFDATA6 = 1U;                    /*  0x3E  0xFF7C   1   -    ivVhti         unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x3F  0xFF7E   1   no   ivVapi         unused by PE */
  INT_CFADDR = 128U;                                      
  INT_CFDATA0 = 1U;                    /*  0x40  0xFF80   1   no   ivVlvi         unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x41  0xFF82   1   no   ivVReserved62  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x42  0xFF84   1   no   ivVReserved61  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x43  0xFF86   1   no   ivVReserved60  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x44  0xFF88   1   no   ivVReserved59  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x45  0xFF8A   1   no   ivVReserved58  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x46  0xFF8C   1   no   ivVpwmesdn     used by PE */
  INT_CFDATA7 = 1U;                    /*  0x47  0xFF8E   1   no   ivVportp       unused by PE */
  INT_CFADDR = 144U;                                      
  INT_CFDATA0 = 1U;                    /*  0x48  0xFF90   1   no   ivVReserved55  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x49  0xFF92   1   no   ivVReserved54  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x4A  0xFF94   1   no   ivVReserved53  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x4B  0xFF96   1   no   ivVReserved52  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x4C  0xFF98   1   no   ivVReserved51  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x4D  0xFF9A   1   no   ivVReserved50  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x4E  0xFF9C   1   no   ivVReserved49  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x4F  0xFF9E   1   no   ivVReserved48  unused by PE */
  INT_CFADDR = 160U;                                      
  INT_CFDATA0 = 1U;                    /*  0x50  0xFFA0   1   no   ivVReserved47  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x51  0xFFA2   1   no   ivVReserved46  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x52  0xFFA4   1   no   ivVReserved45  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x53  0xFFA6   1   no   ivVReserved44  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x54  0xFFA8   1   no   ivVReserved43  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x55  0xFFAA   1   no   ivVReserved42  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x56  0xFFAC   1   no   ivVReserved41  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x57  0xFFAE   1   no   ivVReserved40  unused by PE */
  INT_CFADDR = 176U;                                      
  INT_CFDATA0 = 1U;                    /*  0x58  0xFFB0   1   no   ivVcan0tx      unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x59  0xFFB2   1   no   ivVcan0rx      unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x5A  0xFFB4   1   no   ivVcan0err     unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x5B  0xFFB6   1   no   ivVcan0wkup    unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x5C  0xFFB8   1   no   ivVflash       unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x5D  0xFFBA   1   no   ivVflashfd     unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x5E  0xFFBC   1   no   ivVReserved33  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x5F  0xFFBE   1   no   ivVReserved32  unused by PE */
  INT_CFADDR = 192U;                                      
  INT_CFDATA0 = 1U;                    /*  0x60  0xFFC0   1   no   ivVReserved31  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x61  0xFFC2   1   no   ivVReserved30  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x62  0xFFC4   1   no   ivVcrgscm      unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x63  0xFFC6   1   no   ivVcrgplllck   unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x64  0xFFC8   1   no   ivVReserved27  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x65  0xFFCA   1   no   ivVReserved26  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x66  0xFFCC   1   no   ivVReserved25  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x67  0xFFCE   1   no   ivVportj       unused by PE */
  INT_CFADDR = 208U;                                      
  INT_CFDATA0 = 1U;                    /*  0x68  0xFFD0   1   no   ivVReserved23  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x69  0xFFD2   1   no   ivVatd0        unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x6A  0xFFD4   1   no   ivVsci1        unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x6B  0xFFD6   1   no   ivVsci0        unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x6C  0xFFD8   1   no   ivVspi0        unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x6D  0xFFDA   1   no   ivVtimpaie     used by PE */
  INT_CFDATA6 = 1U;                    /*  0x6E  0xFFDC   1   no   ivVtimpaaovf   used by PE */
  INT_CFDATA7 = 1U;                    /*  0x6F  0xFFDE   1   no   ivVtimovf      used by PE */
  INT_CFADDR = 224U;                                      
  INT_CFDATA0 = 1U;                    /*  0x70  0xFFE0   1   no   ivVtimch7      unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x71  0xFFE2   1   no   ivVtimch6      unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x72  0xFFE4   1   no   ivVtimch5      unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x73  0xFFE6   1   no   ivVtimch4      unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x74  0xFFE8   1   no   ivVtimch3      unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x75  0xFFEA   1   no   ivVtimch2      unused by PE */
  INT_CFDATA6 = 3U;                    /*  0x76  0xFFEC   3   no   ivVtimch1      used by PE */
  INT_CFDATA7 = 1U;                    /*  0x77  0xFFEE   1   no   ivVtimch0      unused by PE */
  INT_CFADDR = 240U;                                      
  INT_CFDATA0 = 1U;                    /*  0x78  0xFFF0   1   no   ivVrti         unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x79  0xFFF2   1   no   ivVirq         unused by PE */
  /* Common initialization of the CPU registers */
  /* RDRP: RDRP7=0,RDRP5=0,RDRP4=0,RDRP3=0,RDRP2=0,RDRP1=0,RDRP0=0 */
  RDRP &= (unsigned char)~(unsigned char)191U;                     
  /* RDRT: RDRT7=0,RDRT6=0,RDRT5=0,RDRT4=0,RDRT3=0,RDRT2=0,RDRT1=0,RDRT0=0 */
  RDRT = 0U;                                      
  /* PTTRR: PTTRR7=1,PTTRR5=1 */
  PTTRR |= (unsigned char)160U;                      
  /* CRGINT: LOCKIE=0,SCMIE=0 */
  CRGINT &= (unsigned char)~(unsigned char)18U;                     
  /* VREGCTRL: LVIE=0 */
  VREGCTRL &= (unsigned char)~(unsigned char)2U;                     
  /* COPCTL: WCOP=0,RSBCK=0,WRTMASK=0,CR2=0,CR1=0,CR0=0 */
  COPCTL = 0U;                                      
  /* RDRIV: RDPE=0,RDPB=0,RDPA=0 */
  RDRIV &= (unsigned char)~(unsigned char)19U;                     
  /* RDRJ: RDRJ7=0,RDRJ6=0 */
  RDRJ &= (unsigned char)~(unsigned char)192U;                     
  /* RDRM: RDRM5=0,RDRM4=0,RDRM3=0,RDRM2=0,RDRM1=0,RDRM0=0 */
  RDRM &= (unsigned char)~(unsigned char)63U;                     
  /* RDRS: RDRS3=0,RDRS2=0,RDRS1=0,RDRS0=0 */
  RDRS &= (unsigned char)~(unsigned char)15U;                     
  /* RDR1AD0: RDR1AD07=0,RDR1AD06=0,RDR1AD05=0,RDR1AD04=0,RDR1AD03=0,RDR1AD02=0,RDR1AD01=0,RDR1AD00=0 */
  RDR1AD0 = 0U;                                      
  /* IRQCR: IRQEN=0 */
  IRQCR &= (unsigned char)~(unsigned char)64U;                     
  /* ### Init_PWM init code */
  /* PWME: PWME7=0,PWME6=0,PWME5=0,PWME4=0,PWME3=0,PWME2=0,PWME1=0,PWME0=0 */
  PWME = 0U;                           /* Disable all PWM channels */
  /* PWMPOL: PPOL7=1,PPOL6=0,PPOL5=1,PPOL4=0,PPOL3=1,PPOL2=0,PPOL1=1,PPOL0=0 */
  PWMPOL = 170U;                                      
  /* PWMCLK: PCLK7=1,PCLK6=0,PCLK5=1,PCLK4=0,PCLK3=1,PCLK2=0,PCLK1=1,PCLK0=0 */
  PWMCLK = 170U;                                      
  /* PWMCAE: CAE7=0,CAE6=0,CAE5=0,CAE4=0,CAE3=0,CAE2=0,CAE1=0,CAE0=0 */
  PWMCAE = 0U;                                      
  /* PWMCTL: CON67=1,CON45=1,CON23=1,CON01=1,PSWAI=0,PFRZ=0 */
  PWMCTL = 240U;                                      
  /* PWMDTY01: PWMDTY01=730 */
  PWMDTY01 = 730U;                            
  /* PWMPER01: PWMPER01=10000 */
  PWMPER01 = 10000U;                            
  /* PWMDTY23: PWMDTY23=100 */
  PWMDTY23 = 100U;                            
  /* PWMPER23: PWMPER23=100 */
  PWMPER23 = 100U;                            
  /* PWMDTY45: PWMDTY45=0 */
  PWMDTY45 = 0U;                            
  /* PWMPER45: PWMPER45=0 */
  PWMPER45 = 0U;                            
  /* PWMDTY67: PWMDTY67=100 */
  PWMDTY67 = 100U;                            
  /* PWMPER67: PWMPER67=100 */
  PWMPER67 = 100U;                            
  /* PWMSCLA: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=1,BIT1=0,BIT0=1 */
  PWMSCLA = 5U;                                      
  /* PWMSCLB: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=1,BIT1=0,BIT0=1 */
  PWMSCLB = 5U;                                      
  /* PWMPRCLK: PCKB2=0,PCKB1=0,PCKB0=1,PCKA2=0,PCKA1=1,PCKA0=1 */
  PWMPRCLK = 19U;                                      
  /* PWMSDN: PWMIF=1,PWMIE=0,PWMRSTRT=1,PWMLVL=0,PWM7IN=0,PWM7INL=0,PWM7ENA=0 */
  PWMSDN = 160U;                                      
  /* PWME: PWME7=1,PWME6=0,PWME5=1,PWME4=0,PWME3=1,PWME2=0,PWME1=1,PWME0=0 */
  PWME = 170U;                         /* Enable only configured PWM channels */
  /* ### Init_PIT init code */
  /* PITCFLMT: PITE=0 */
  PITCFLMT &= (unsigned char)~(unsigned char)128U;                     
  /* PITMTLD0: PMTLD7=1,PMTLD6=1,PMTLD5=0,PMTLD4=0,PMTLD3=0,PMTLD2=1,PMTLD1=1,PMTLD0=1 */
  PITMTLD0 = 199U;                                      
  /* PITMTLD1: PMTLD7=0,PMTLD6=0,PMTLD5=1,PMTLD4=1,PMTLD3=0,PMTLD2=0,PMTLD1=0,PMTLD0=1 */
  PITMTLD1 = 49U;                                      
  /* PITLD0: PLD15=0,PLD14=0,PLD13=0,PLD12=0,PLD11=1,PLD10=1,PLD9=1,PLD8=1,PLD7=1,PLD6=0,PLD5=0,PLD4=1,PLD3=1,PLD2=1,PLD1=1,PLD0=1 */
  PITLD0 = 3999U;                            
  /* PITMUX: PMUX3=0,PMUX2=0,PMUX1=0,PMUX0=0 */
  PITMUX = 0U;                                      
  /* PITCE: PCE3=0,PCE2=0,PCE1=0,PCE0=1 */
  PITCE = 1U;                                      
  /* PITTF: PTF3=0,PTF2=0,PTF1=0,PTF0=1 */
  PITTF = 1U;                                      
  /* PITINTE: PINTE3=0,PINTE2=0,PINTE1=0,PINTE0=0 */
  PITINTE = 0U;                                      
  /* PITCFLMT: PITE=1,PITSWAI=0,PITFRZ=0,PFLMT1=0,PFLMT0=0 */
  PITCFLMT = 128U;                                      
  /* ### Init_TIM init code */
  /* TSCR1: TEN=0 */
  TSCR1 &= (unsigned char)~(unsigned char)128U;                     
  /* TIE: C7I=0,C6I=0,C5I=0,C4I=0,C3I=0,C2I=0,C1I=0,C0I=0 */
  TIE = 0U;                                      
  /* PACTL: PAEN=0,PAI=0 */
  PACTL &= (unsigned char)~(unsigned char)65U;                     
  /* PTTRR: PTTRR7=0,PTTRR6=0,PTTRR5=0,PTTRR4=0,PTTRR2=0,PTTRR1=0,PTTRR0=0 */
  PTTRR = 0U;                                      
  /* TIOS: IOS7=0,IOS6=0,IOS5=0,IOS4=0,IOS3=0,IOS2=0,IOS1=0,IOS0=0 */
  TIOS = 0U;                                      
  /* TC1: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  TC1 = 0U;                            
  /* OCPD: OCPD7=0,OCPD6=0,OCPD5=0,OCPD4=0,OCPD3=0,OCPD2=0,OCPD1=1,OCPD0=0 */
  OCPD = 2U;                                      
  /* OC7M: OC7M7=0,OC7M6=0,OC7M5=0,OC7M4=0,OC7M3=0,OC7M2=0,OC7M1=0,OC7M0=0 */
  OC7M = 0U;                                      
  /* OC7D: OC7D7=0,OC7D6=0,OC7D5=0,OC7D4=0,OC7D3=0,OC7D2=0,OC7D1=0,OC7D0=0 */
  OC7D = 0U;                                      
  /* TTOV: TOV7=0,TOV6=0,TOV5=0,TOV4=0,TOV3=0,TOV2=0,TOV1=0,TOV0=0 */
  TTOV = 0U;                                      
  /* TCTL1: OM7=0,OL7=0,OM6=0,OL6=0,OM5=0,OL5=0,OM4=0,OL4=0 */
  TCTL1 = 0U;                                      
  /* TCTL2: OM3=0,OL3=0,OM2=0,OL2=0,OM1=0,OL1=0,OM0=0,OL0=0 */
  TCTL2 = 0U;                                      
  /* TCTL3: EDG7B=0,EDG7A=0,EDG6B=0,EDG6A=0,EDG5B=0,EDG5A=0,EDG4B=0,EDG4A=0 */
  TCTL3 = 0U;                                      
  /* TCTL4: EDG3B=0,EDG3A=0,EDG2B=0,EDG2A=0,EDG1B=0,EDG1A=1,EDG0B=0,EDG0A=0 */
  TCTL4 = 4U;                                      
  /* TFLG1: C7F=1,C6F=1,C5F=1,C4F=1,C3F=1,C2F=1,C1F=1,C0F=1 */
  TFLG1 = 255U;                                      
  /* TFLG2: TOF=1 */
  TFLG2 = 128U;                                      
  /* TIE: C7I=0,C6I=0,C5I=0,C4I=0,C3I=0,C2I=0,C1I=1,C0I=0 */
  TIE = 2U;                                      
  /* TSCR2: TOI=0,TCRE=0,PR2=0,PR1=0,PR0=0 */
  TSCR2 = 0U;                                      
  /* PACNT: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  PACNT = 0U;                            
  /* PTPSR: PTPS7=0,PTPS6=0,PTPS5=0,PTPS4=0,PTPS3=0,PTPS2=0,PTPS1=0,PTPS0=0 */
  PTPSR = 0U;                                      
  /* TSCR1: TEN=1,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=0 */
  TSCR1 = 128U;                                      
  /* PAFLG: PAOVF=1,PAIF=1 */
  PAFLG = 3U;                                      
  /* PACTL: PAEN=0,PAMOD=0,PEDGE=0,CLK1=0,CLK0=0,PAOVI=0,PAI=0 */
  PACTL = 0U;                                      
  /* ### */
  /* Initial interrupt priority */
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  asm CLI;                             /* Enable interrupts */
  /*lint -restore Enable MISRA rule (1.1) checking. */
} /*MCU_init*/

#pragma MESSAGE DEFAULT C12056

/*lint -save  -e765 Disable MISRA rule (8.10) checking. */
#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isr_default
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isr_default(void)
{
  /* Write your interrupt code here ... */
   PORTB=PORTB&0b11110111;
}
/* end of isr_default */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVpit0
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVpit0(void)
{
   PITTF_PTF0=1; 
   
   PID_speed();
  // setspeed(50,1);
}
/* end of isrVpit0 */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVpwmesdn
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVpwmesdn(void)
{
  /* Write your interrupt code here ... */
//  PORTB=PORTB&0b11111101;
}
/* end of isrVpwmesdn */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVtimpaie
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVtimpaie(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVtimpaie */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVtimpaaovf
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVtimpaaovf(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVtimpaaovf */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVtimovf
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVtimovf(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVtimovf */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVtimch1
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVtimch1(void)
{
  /* Write your interrupt code here ... */
   TFLG1_C1F=1;
   v_flag=1;
   TIE1_C=0;//πÿ±’÷–∂œ
   PORTB_PB0=~PORTB_PB0;
}
/* end of isrVtimch1 */
#pragma CODE_SEG DEFAULT


/*lint -restore Enable MISRA rule (8.10) checking. */

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */




/* Interrupt vector table */


/* ISR prototype */
typedef void (*near tIsrFunc)(void);

#ifndef UNASSIGNED_ISR
  #define UNASSIGNED_ISR isr_default   /* unassigned interrupt service routine */
#endif
/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
static const tIsrFunc _InterruptVectorTable[] @0xFF10U = { /* Interrupt vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* ISR name                               No.  Address  Pri Name           Description */
  &UNASSIGNED_ISR,                      /* 0x08  0xFF10   -   ivVsi          unused by PE */
  &UNASSIGNED_ISR,                      /* 0x09  0xFF12   -   ivVsyscall     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0A  0xFF14   1   ivVReserved118 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0B  0xFF16   1   ivVReserved117 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0C  0xFF18   1   ivVReserved116 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0D  0xFF1A   1   ivVReserved115 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0E  0xFF1C   1   ivVReserved114 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0F  0xFF1E   1   ivVReserved113 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x10  0xFF20   1   ivVReserved112 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x11  0xFF22   1   ivVReserved111 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x12  0xFF24   1   ivVReserved110 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x13  0xFF26   1   ivVReserved109 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x14  0xFF28   1   ivVReserved108 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x15  0xFF2A   1   ivVReserved107 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x16  0xFF2C   1   ivVReserved106 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x17  0xFF2E   1   ivVReserved105 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x18  0xFF30   1   ivVReserved104 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x19  0xFF32   1   ivVReserved103 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1A  0xFF34   1   ivVReserved102 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1B  0xFF36   1   ivVReserved101 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1C  0xFF38   1   ivVReserved100 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1D  0xFF3A   1   ivVReserved99  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1E  0xFF3C   1   ivVReserved98  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1F  0xFF3E   1   ivVatd0compare unused by PE */
  &UNASSIGNED_ISR,                      /* 0x20  0xFF40   1   ivVReserved96  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x21  0xFF42   1   ivVReserved95  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x22  0xFF44   1   ivVReserved94  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x23  0xFF46   1   ivVReserved93  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x24  0xFF48   1   ivVReserved92  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x25  0xFF4A   1   ivVReserved91  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x26  0xFF4C   1   ivVReserved90  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x27  0xFF4E   1   ivVReserved89  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x28  0xFF50   1   ivVReserved88  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x29  0xFF52   1   ivVReserved87  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2A  0xFF54   1   ivVReserved86  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2B  0xFF56   1   ivVReserved85  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2C  0xFF58   1   ivVReserved84  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2D  0xFF5A   1   ivVReserved83  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2E  0xFF5C   1   ivVReserved82  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2F  0xFF5E   1   ivVReserved81  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x30  0xFF60   1   ivVReserved79  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x31  0xFF62   1   ivVReserved78  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x32  0xFF64   1   ivVReserved77  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x33  0xFF66   1   ivVReserved76  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x34  0xFF68   1   ivVReserved75  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x35  0xFF6A   1   ivVReserved74  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x36  0xFF6C   1   ivVReserved73  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x37  0xFF6E   1   ivVReserved72  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x38  0xFF70   1   ivVReserved71  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x39  0xFF72   1   ivVReserved70  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3A  0xFF74   1   ivVpit3        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3B  0xFF76   1   ivVpit2        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3C  0xFF78   1   ivVpit1        unused by PE */
  &isrVpit0,                            /* 0x3D  0xFF7A   4   ivVpit0        used by PE */
  &UNASSIGNED_ISR,                      /* 0x3E  0xFF7C   1   ivVhti         unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3F  0xFF7E   1   ivVapi         unused by PE */
  &UNASSIGNED_ISR,                      /* 0x40  0xFF80   1   ivVlvi         unused by PE */
  &UNASSIGNED_ISR,                      /* 0x41  0xFF82   1   ivVReserved62  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x42  0xFF84   1   ivVReserved61  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x43  0xFF86   1   ivVReserved60  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x44  0xFF88   1   ivVReserved59  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x45  0xFF8A   1   ivVReserved58  unused by PE */
  &isrVpwmesdn,                         /* 0x46  0xFF8C   1   ivVpwmesdn     used by PE */
  &UNASSIGNED_ISR,                      /* 0x47  0xFF8E   1   ivVportp       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x48  0xFF90   1   ivVReserved55  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x49  0xFF92   1   ivVReserved54  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4A  0xFF94   1   ivVReserved53  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4B  0xFF96   1   ivVReserved52  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4C  0xFF98   1   ivVReserved51  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4D  0xFF9A   1   ivVReserved50  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4E  0xFF9C   1   ivVReserved49  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4F  0xFF9E   1   ivVReserved48  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x50  0xFFA0   1   ivVReserved47  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x51  0xFFA2   1   ivVReserved46  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x52  0xFFA4   1   ivVReserved45  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x53  0xFFA6   1   ivVReserved44  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x54  0xFFA8   1   ivVReserved43  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x55  0xFFAA   1   ivVReserved42  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x56  0xFFAC   1   ivVReserved41  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x57  0xFFAE   1   ivVReserved40  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x58  0xFFB0   1   ivVcan0tx      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x59  0xFFB2   1   ivVcan0rx      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5A  0xFFB4   1   ivVcan0err     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5B  0xFFB6   1   ivVcan0wkup    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5C  0xFFB8   1   ivVflash       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5D  0xFFBA   1   ivVflashfd     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5E  0xFFBC   1   ivVReserved33  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5F  0xFFBE   1   ivVReserved32  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x60  0xFFC0   1   ivVReserved31  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x61  0xFFC2   1   ivVReserved30  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x62  0xFFC4   1   ivVcrgscm      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x63  0xFFC6   1   ivVcrgplllck   unused by PE */
  &UNASSIGNED_ISR,                      /* 0x64  0xFFC8   1   ivVReserved27  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x65  0xFFCA   1   ivVReserved26  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x66  0xFFCC   1   ivVReserved25  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x67  0xFFCE   1   ivVportj       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x68  0xFFD0   1   ivVReserved23  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x69  0xFFD2   1   ivVatd0        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6A  0xFFD4   1   ivVsci1        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6B  0xFFD6   1   ivVsci0        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6C  0xFFD8   1   ivVspi0        unused by PE */
  &isrVtimpaie,                         /* 0x6D  0xFFDA   1   ivVtimpaie     used by PE */
  &isrVtimpaaovf,                       /* 0x6E  0xFFDC   1   ivVtimpaaovf   used by PE */
  &isrVtimovf,                          /* 0x6F  0xFFDE   1   ivVtimovf      used by PE */
  &UNASSIGNED_ISR,                      /* 0x70  0xFFE0   1   ivVtimch7      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x71  0xFFE2   1   ivVtimch6      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x72  0xFFE4   1   ivVtimch5      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x73  0xFFE6   1   ivVtimch4      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x74  0xFFE8   1   ivVtimch3      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x75  0xFFEA   1   ivVtimch2      unused by PE */
  &isrVtimch1,                          /* 0x76  0xFFEC   3   ivVtimch1      used by PE */
  &UNASSIGNED_ISR,                      /* 0x77  0xFFEE   1   ivVtimch0      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x78  0xFFF0   1   ivVrti         unused by PE */
  &UNASSIGNED_ISR,                      /* 0x79  0xFFF2   1   ivVirq         unused by PE */
  &UNASSIGNED_ISR,                      /* 0x7A  0xFFF4   -   ivVxirq        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x7B  0xFFF6   -   ivVswi         unused by PE */
  &UNASSIGNED_ISR                       /* 0x7C  0xFFF8   -   ivVtrap        unused by PE */
};

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
static const tIsrFunc _ResetVectorTable[] @0xFFFAU = { /* Reset vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* Reset handler name                    Address Name            Description */
  &MCU_init_reset,                      /* 0xFFFA  ivVcop          unused by PE */
  &MCU_init_reset,                      /* 0xFFFC  ivVclkmon       unused by PE */
  &MCU_init_reset                       /* 0xFFFE  ivVreset        used by PE */
};


/* END MCUinit */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
